/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stm32f407xx.h>
#include <stm32f407xx_gpio_driver.h>
void delay(void)
{
    for(uint32_t i=0;i<500000;i++);
}
void InitFunction(GPIO_Handle_t *pGPIOHandle,GPIO_RegDef_t * port,uint8_t PinNumber, uint8_t PinMode, uint8_t PinSpeed, uint8_t PinOptype, uint8_t PinPuPdControl)
{
    pGPIOHandle->pGPIOx=port;
    pGPIOHandle->GPIO_PinConfig.GPIO_PinNumber = PinNumber;
    pGPIOHandle->GPIO_PinConfig.GPIO_PinMode = PinMode;
    pGPIOHandle->GPIO_PinConfig.GPIO_PinSpeed = PinSpeed;
    pGPIOHandle->GPIO_PinConfig.GPIO_PinOptype = PinOptype;
    pGPIOHandle->GPIO_PinConfig.GPIO_PinPuPdControl = PinPuPdControl;
    GPIO_PeriClockControl(port,ENABLE);
    GPIO_Init(pGPIOHandle);
}
int main(void)
{
    GPIO_Handle_t GpioLed;
    InitFunction(&GpioLed,GPIOD,GPIO_PIN_NO_12,GPIO_MODE_OUTPUT,GPIO_SPEED_FAST,GPIO_OP_TYPE_OP,GPIO_PIN_PD);
    while(1)
    {
        //uint8_t i=GPIO_PIN_NO_12;
        // for(i;i<(GPIO_PIN_NO_15 + 1);i++)
        // {
        //     InitFunction(&GpioLed,GPIOD,i,GPIO_MODE_OUTPUT,GPIO_SPEED_FAST,GPIO_OP_TYPE_OP,GPIO_PIN_PD);
        //     GPIO_WriteToOutputPin(GPIOD,GpioLed.GPIO_PinConfig.GPIO_PinNumber,GPIO_PIN_SET);
        //     delay();
        //     GPIO_WriteToOutputPin(GPIOD,GpioLed.GPIO_PinConfig.GPIO_PinNumber,GPIO_PIN_RESET);
        //     delay();
        //     if (i==GPIO_PIN_NO_15)
        //     {
        //         i=GPIO_PIN_NO_11;
        //     }

        // }
            GPIO_WriteToOutputPin(GPIOD,GpioLed.GPIO_PinConfig.GPIO_PinNumber,GPIO_PIN_SET);
            delay();
            GPIO_WriteToOutputPin(GPIOD,GpioLed.GPIO_PinConfig.GPIO_PinNumber,GPIO_PIN_RESET);
            delay();
    }
}
