/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stm32f407xx.h>
#include <stm32f407xx_gpio_driver.h>
void delay(void)
{
    for(uint32_t i=0;i<500000/2;i++);
}
void InitFunction(GPIO_Handle_t *pGPIOHandle,GPIO_RegDef_t * port,uint8_t PinNumber, uint8_t PinMode, uint8_t PinSpeed, uint8_t PinPuPdControl)
{
    pGPIOHandle->pGPIOx=port;
    pGPIOHandle->GPIO_PinConfig.GPIO_PinNumber = PinNumber;
    pGPIOHandle->GPIO_PinConfig.GPIO_PinMode = PinMode;
    pGPIOHandle->GPIO_PinConfig.GPIO_PinSpeed = PinSpeed;
    pGPIOHandle->GPIO_PinConfig.GPIO_PinPuPdControl = PinPuPdControl;
    GPIO_PeriClockControl(port,ENABLE);
    GPIO_Init(pGPIOHandle);
}
int main(void)
{
    GPIO_Handle_t GpioLed,GPIOBtn;
    GpioLed.pGPIOx = GPIOD;
    GpioLed.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_12;
    GpioLed.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_OUTPUT;
    GpioLed.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_FAST;
    GpioLed.GPIO_PinConfig.GPIO_PinOptype = GPIO_OP_TYPE_PP;
    GpioLed.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_NO_PUPD;
    GPIO_PeriClockControl(GPIOD,ENABLE);
    GPIO_Init(&GpioLed);
    InitFunction(&GPIOBtn,GPIOA,GPIO_PIN_NO_0,GPIO_MODE_INPUT,GPIO_SPEED_FAST,GPIO_NO_PUPD);
    while(1)
    {
    	if (GPIO_ReadFromInputPin(GPIOA,GPIO_PIN_NO_0) == 1)
    	{
    		delay();
    		GPIO_WriteToOutputPin(GPIOD,GPIO_PIN_NO_12,GPIO_PIN_SET);
    		//delay();
    	}
    	else
    	{
    		GPIO_WriteToOutputPin(GPIOD,GPIO_PIN_NO_12,GPIO_PIN_RESET);
    	}
    }
    return 0;
}
